test:
    image: python:2.7
    script:
        - virtualenv env
        - source env/bin/activate
        - apt-get install libpq-dev python-dev
        - pip install -r requirements.dev.txt
        - pip install psycopg2
        - nosetests tests
            
cache:
    paths:
      - env/