test:
    script:
        - apt-get install -y python-virtualenv
        - apt-get install -y python-pip
        - virtualenv env
        - source env/bin/activate
        - pip install -r requirements.txt
        - nosetests tests
            
cache:
    paths:
      - env/